config/routes.rb
Rails.application.routes.draw do

  root 'public/welcome#index'

  get 'terms/',   to: 'public/terms#index'
  get 'about/',   to: 'public/terms#about_page'
  get 'faq/'  ,   to: 'public/common_questions#index'
  get 'sign-up',  to: 'public/registrations#new'
  post 'sign-up', to: 'public/registrations#create'
  get 'sign-out', to: 'public/authentication#destroy'
  get 'sign-in',  to: 'public/authentication#new'
  post'sign-in',  to: 'public/authentication#create'


  resources :tasks, module: :private do
    resources :comments, only:[:create]
  end

  resources :users, module: :private
  resources :projects, module: :private do
    resources :tasks
    resources :memberships, except:[:show, :edit]
  end

  resources :tracker_projects, only:[:show], module: :private

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy
  validates :description, presence: true
end

app/controllers/private/tasks_controller.rb
class Private::TasksController < PrivateController
  before_action :find_and_set_project
  before_action :set_task, only: [:show, :edit, :update]
  before_action :ensure_project_member_or_admin

  def index
    @tasks = @project.tasks
  end

  def show
    @comments = @task.comments.all
    @comment = @task.comments.new
  end

  def new
    @task = Task.new
  end

  def create
    task = @project.tasks.new(task_params)
    if task.save
      flash[:notice] = "Task was successfully created"
      redirect_to project_task_path(@project, task)
    else
      @task = task
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
       flash[:notice] = "Task was successfully updated"
       redirect_to project_task_path(@project, @task)
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to project_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date, :project_id)
  end

  def set_task
    @task = Task.where(project_id: @project.id).find(params[:id])
  end

  def find_and_set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < PrivateController
  before_action :set_task, only: [:show, :edit, :update]
  before_action :ensure_current_user
  before_action :find_and_set_project
  before_action :ensure_project_member_or_admin
  before_action :ensure_task_belongs_to_project, only:[:show]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.new
  end

  def create
    task = @project.tasks.new(task_params)
    if task.save
      flash[:notice] = "Task was successfully created"
      redirect_to project_task_path(@project, task)
    else
      @task = task
      render :new
    end
  end

  def show
    @comments = @task.comments.all
    @comment = @task.comments.new
  end

  def edit
  end

  def update
    task = @project.tasks.find(params[:id])
    if task.update(task_params)
       flash[:notice] = "Task was successfully updated"
       redirect_to project_task_path(@project, task)
    else
      @task = task
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to project_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date, :project_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def find_and_set_project
    @project = Project.find(params[:project_id])
  end

  def ensure_task_belongs_to_project
    if !@project.tasks.include?(@task)
      flash[:warning] = 'You do not have access to that project'
      redirect_to projects_path
    end
  end

end

app/views/tasks/_form.html.haml
= form_for(@task, html: {class: 'form-horizontal'}) do |f|
  .form-group
    = f.label :description, class: 'col-md-1 control-label'
    .col-md-3
      = f.text_field :description, class: 'form-control'

  - unless @task.new_record?
    .form-group
      .col-md-3.col-md-offset-1
        =f.check_box :complete
        = f.label :complete

  .form-group
    .col-md-6.col-md-offset-1
      = f.submit class:'btn btn-primary'
      = link_to 'Cancel', tasks_path, class: 'btn btn-default'

app/views/tasks/edit.html.haml
.page-header
  .h1 Editing Task
.breadcrumb
  %li= link_to 'Tasks',tasks_path
  %li= link_to @task.description, task_path(@task)
  %li.active Edit
= render 'form'

app/views/tasks/index.html.haml
.page-header
  .pull-right
    = link_to 'New Task', new_task_path, class:'btn btn-info'
  %h1 Tasks
%table.table
  %thead
    %tr
      %th{colspan: 2} Description
  %tbody
    - @tasks.each do |task|
      %tr
        - if task.complete
          %td
            %s= link_to task.description,task_path(task)
        - else
          %td= link_to task.description, task_path(task)
        %td.text-right= link_to 'Edit', edit_task_path(task), class: 'btn btn-info'
        %td= link_to 'Delete', task_path(task), class: 'btn btn-danger', method: :delete