config/routes.rb
Rails.application.routes.draw do

  root 'public/welcome#index'

  get 'terms/',   to: 'public/terms#index'
  get 'about/',   to: 'public/terms#about_page'
  get 'faq/'  ,   to: 'public/common_questions#index'
  get 'sign-up',  to: 'public/registrations#new'
  post 'sign-up', to: 'public/registrations#create'
  get 'sign-out', to: 'public/authentication#destroy'
  get 'sign-in',  to: 'public/authentication#new'
  post'sign-in',  to: 'public/authentication#create'


  resources :tasks, module: :private do
    resources :comments, only:[:create]
  end

  resources :users, module: :private
  resources :projects, module: :private do
    resources :tasks
    resources :memberships, except:[:show, :edit]
  end

  resources :tracker_projects, only:[:show], module: :private

end

app/controllers/authentication_controller.rb
class AuthenticationController < PublicController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed in"
      redirect_to session[:return_to] || projects_path
    else
      flash[:error] = "Email / Password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/views/authentication/new.haml
.well.col-md-6.col-md-offset-3
  .page-header
    %h3 Sign into gCamp
  -if flash[:error]
    %h5.text-danger= flash[:error]
  = form_tag sign_in_path, class: 'form' do
    .form-group
      = label_tag :email, nil, class: 'control-label'
      = email_field_tag :email, nil, class: 'form-control'
    .form-group
      = label_tag :password, nil , class: 'control-label'
      = password_field_tag :password, nil, class: 'form-control'
    .form-group
      = submit_tag "Sign In", class: 'btn btn-default'